#!/usr/bin/env bash

#-----------------------------------------------------------------------------
# source setup and helper functions
source "${SETUP_FILE}"
source call_bashhelper

#-----------------------------------------------------------------------------
# Function to check and copy anatomical T1w data
check_and_copy_anat() {
  local func_dir="$1"
  local base_path="$2"
  local anat_dir_level="$3"  # Level of hierarchy for anatomical search (5 or 6)
  local fs_dir="$4"          # FreeSurfer directory
  local sub_name="$5"
  local base="$6"
  local data="$7"

  local anat
  anat=$(
    find -L "${func_dir}/${base_path}/anat" \
    -type f \
    -name "*T1w.nii.gz" \
    2>/dev/null
  )

  if [[ -z "${anat}" ]]; then
    local anat_dir
    anat_dir=$(find_hierarchical_anatomy "${anat_dir_level}")
    local diff_anat
    diff_anat=$(
      find -L "${anat_dir}/${base_path}" \
      -type f \
      -name "*T1w.nii.gz" \
      2>/dev/null
    )

    if [[ -n "${diff_anat}" ]]; then
      # Create anat directory if it doesn't exist
      mkdir -p "${func_dir}/${base_path}/anat"

      # Copy the T1w file
      cp "${diff_anat}" "${func_dir}/${base_path}/anat"
      echo "Copied \"${diff_anat}\" to ${func_dir}/${base_path}/anat"
    else
      # Try FreeSurfer rawavg.mgz if available
      local fs_rawavg="${fs_dir}/${sub_name}/mri/rawavg.mgz"
      if [[ -f "${fs_rawavg}" ]]; then
        cmd=(
          call_mriconvert
          "${fs_rawavg}"
          "${func_dir}/${base_path}/anat/${base}_acq-${DATA_UPR}_T1w.nii.gz"
        )

        print_cmd "${cmd[@]}" && eval "${cmd[@]}"
        if [[ $? -ne 0 ]]; then
          print_error_msg "$(basename ${0})" "call_mriconvert"
          exit 1
        fi          
      else
        print_file_not_in_dir "${sub_name}" "*T1w.nii.gz" "${anat_dir}" "Please copy a file containing \"_T1w.nii.gz\" to \""${anat_dir}"\"."
        exit 1
      fi
    fi    
  fi
}

#-----------------------------------------------------------------------------
# Function to find functional data
find_func_data() {
  local func_dir="$1"
  local base_path="$2"
  local input_dir="$3"

  if [[ -n "${func_dir}" ]]; then
    # Functional data in a separate directory
    find -L "${func_dir}/${base_path}/func" -type f -name "*bold.nii.gz" 2>/dev/null
  else
    # Functional data in the same directory as anatomical data
    find -L "${input_dir}/func" -type f -name "*bold.nii.gz" 2>/dev/null
  fi
}

#-----------------------------------------------------------------------------
# Function to manage fMRIPrep working directory and cleanup options
manage_fmriprep_workdir() {
  local workdir="$1"
  local project="$2"
  local sub_id="$3"
  local remove_surf_wf="$4"
  local remove_wf="$5"
  local overwrite="$6"
  local local_bool="$7"
  local runs=("${@:8}")  # Capture remaining arguments as an array

  # Ensure working directory exists
  if [[ ! -d "${workdir}" ]]; then
    mkdir -p "${workdir}"
  fi

  # Locate workflow folder
  local wf_folder
  wf_folder=$(
    find "${workdir}" \
    -maxdepth 1 \
    -type d \
    -name "fmriprep*" -and -name "*wf" \
    2>/dev/null
  )

  # Remove surface reconstruction workflow if specified
  if [[ -d "${wf_folder}" ]]; then

    # find subject wf folder
    subj_wf=$(
      find "${wf_folder}" \
      -maxdepth 1 \
      -name "*_${sub_id}_wf"
    )

    if [[ -d "${subj_wf}" ]]; then
      # remove FreeSurfer recon workflow
      if [[ "${remove_surf_wf}" -eq 1 ]]; then
        surf_wf=$(find "${subj_wf}" -type d -name "surface_recon_wf")
        if [[ -d "${surf_wf}" ]]; then
          if [[ ${local_bool} -eq 1 ]]; then
            echo -e "Execute [reason]: Removing ${BOLD_MAGENTA}${surf_wf}${RESET}"
          fi
          rm -r "${surf_wf}" 2>/dev/null
        else
          if [[ ${local_bool} -eq 1 ]]; then
            echo -e "Execute [reason]: Could not find ${BOLD_RED}surface_recon_wf${RESET} folder in ${BOLD_MAGENTA}${subj_wf}${RESET}"
          fi
        fi
      # remove full workflow (BOLD, FMAP, & ANAT)
      elif [[ "${remove_wf}" -eq 1 ]]; then
        if [[ ${local_bool} -eq 1 ]]; then
          echo -e "Execute [reason]: Removing ${BOLD_MAGENTA}${subj_wf}${RESET}"
        fi
        rm -r "${subj_wf}" 2>/dev/null
      # Remove workflow folders for specific runs or all runs
      elif [[ "${overwrite}" -eq 1 ]]; then
        if [[ ${#runs[@]} -gt 0 ]]; then
          for r in "${runs[@]}"; do
            if [[ ${local_bool} -eq 1 ]]; then
              echo -e "Execute [reason]: Removing workflow folders with ${BOLD_RED}run-${r}${RESET} in ${BOLD_MAGENTA}${subj_wf}${RESET}"
            fi
            rm -r "${subj_wf}/"*run_"${r}"* 2>/dev/null
          done
        else
          if [[ ${local_bool} -eq 1 ]]; then
            echo -e "Execute [reason]: Removing workflow folders with ${BOLD_RED}run-*${RESET} in ${BOLD_MAGENTA}${subj_wf}${RESET}"
          fi

          local ddir
          ddir=(
            $(
              find "${subj_wf}" \
              -maxdepth 1 \
              -type d \
              -name "*run*" -and -name "*_wf" | \
              sort
            )
          )
          for d in "${ddir[@]}"; do echo -e " ${BOLD_GREEN}${d}${RESET}"; rm -r "${d}" 2>/dev/null; done
        fi
      fi
    else
      if [[ ${local_bool} -eq 1 ]]; then
        echo -e "Execute [reason]: No folder with ${BOLD_RED}*_${sub_id}_wf${RESET} in ${BOLD_MAGENTA}${wf_folder}${RESET}"
      fi
    fi
  else
    if [[ ${local_bool} -eq 1 ]]; then
      echo -e "Execute [reason]: No folder with ${BOLD_RED}-name "fmriprep*" -and -name "*wf"${RESET} in ${BOLD_MAGENTA}${workdir}${RESET}"
    fi
  fi
}

#-----------------------------------------------------------------------------
# config file function
generate_config_file() {
  local conf=$1
  shift
  local runs=("$@")
  local conf_file=""

  if [[ -z $conf ]]; then
    if ((${#runs[@]} > 0)); then
      local workdir=${WORKDIR:-$DIR_DATA_HOME}
      conf_file="${workdir}/run_conf.json"

      local run_json=""
      local run

      for run in "${runs[@]}"; do
        printf -v run_json '%s"%s",' "$run_json" "$run"
      done

      run_json="[${run_json%,}]"

      cat > "$conf_file" <<EOF
{
  "bold": {
    "run": $run_json
  },
  "fmap": {
    "run": $run_json
  }
}
EOF
    fi
  else
    if ((${#runs[@]} > 0)); then
      echo "WARNING: Specific runs and a configuration file were both provided." >&2
      echo "The configuration file will determine run selection." >&2

      while true; do
        read -r -p "Do you want to proceed? (yes/no) " yn
        case $yn in
          y|yes) break ;;
          n|no)
            echo "Exiting..." >&2
            return 1
            ;;
          *)
            echo 'Invalid response; use "yes", "y", "no", or "n".' >&2
            ;;
        esac
      done
    fi

    conf_file=$conf
  fi

  printf '%s\n' "$conf_file"
}

#-----------------------------------------------------------------------------
# Create help text
function Usage {
    cat <<USAGE

---------------------------------------------------------------------------------------------------
spinoza_fmriprep

preprocess structural and functional data with fMRIprep. It uses the singularity container in de-
fined in the FPREP_SIMG-variable in the setup file. You can also run fmriprep through a docker 
image, in which case 'fmriprep-docker' needs to be installed. To run fmriprep through docker, 
specify the '--docker' flag when running this module (e.g., 'master -m 15 --func --docker'). If we 
do not have access to singularity or docker, we can run fmriprep through the BIDSApp. 

By default, this runs the anatomical pipeline only. This is to optimize the surface reconstruction
first before injecting the functional data. The anatomical file can be in several places, which 
will be assessed hierarchically with 'find_hierarchical_anatomy' function in call_bashhelper. 
We'll look consecutively in:
  - DIR_DATA_DERIV/masked_mp2rage (output from master -m 13   [spinoza_masking])
  - DIR_DATA_DERIV/cat12          (output from master -m 09   [spinoza_brainextraction])
  - DIR_DATA_DERIV/denoised       (output from master -m 08   [spinoza_biassanlm])
  - DIR_DATA_DERIV/pymp2rage      (output from master -m 04   [spinoza_qmrimaps])
  - DIR_DATA_HOME (standard BIDS) (output from master -m 02a  [spinoza_scanner2bids]) 

If you have a T2-weighted image as well, you can specify the root directory to that image. If it
exists, we will copy it to the directory where the T1-weighted is located (<input directory>) so
that it is included by fMRIprep.

Usage:
  spinoza_fmriprep [arguments] [options] <anat dir> <derivatives folder> <mode> <T2 dir>

Arguments:
  -a <keep>       if you're running fMRIprep with MNI152* as output space, you're creating massive
                  files; oftentimes, you're mostly interested in the registration matrices, so by
                  default I'll remove the output nifti's so that the folder is not clogged. With 
                  this argument you can specify which runs to keep. Again, if not specified, all
                  nifti-files with space-MNI152*.nii.gz will be removed. The transformation matri-
                  ces will be left alone. Use '-a all' to keep all runs (not recommended..)
  -f <func dir>   directory containing functional data; used after running FreeSurfer outside of
                  fMRIprep <optional>
  -j <cpus>       number of cores to use (default is 1)
  -k <file>       specify a file with additional arguments, similar to FreeSurfer's expert options.
                  See fmriproc/misc/fprep_options for an example. Please make sure you have a 
                  final empty white space at the end of the file, otherwise the parser gets confu-
                  sed. For VSCode: https://stackoverflow.com/a/44704969.
  -n <session>    session ID (e.g., 1, 2, or none); used to check for T1w-image. fMRIprep will do 
                  all sessions it finds in the project root regardless of this argument. Use the 
                  bids filter file ('-u' flag) if you want fMRIPrep to to specific sessions/tasks/
                  acquisitions.
  -q <queue>      submit jobs to a specific queue. Defaults to SGE_QUEUE_LONG in spinoza_setup
  -r <runs>       re-)run specific runs by removing existing single_subject_<subj_id>_wf/
                  func_preproc_ses_1_*_run_<run_id>_*_wf folders. This should re-use the existing 
                  files for other runs, but re-run completely the requested runs
  -s <subject>    subject ID (e.g., 01). Can also be comma-separated list: 01,02,05
  -t <task>       By default, the pipeline is setup to run fMRIPrep with '--anat-only'. You can in-
                  ject functional data with the '-t' flag; if you want ALL your tasks to be 
                  included, use '-t func'. If you have a specific task that needs to be processed 
                  (in case another task is already done), use '-t <task_id>'.
  -u <config>     configuration file as specified in /misc/fmriprep_config?.json
  -w <workdir>    custom working directory; defaults to PATH_HOME/fmriprep/<PROJECT>
  -x <kwargs>     additional arguments passed to call_fmriprep / fMRIprep. Format should be
                  comma-separated flags:
                    - flag with value: <flag>=<value>
                    - flag only:       <flag>

                  Example:
                    -x "--derivatives=/path/to/derivatives,----bold2t1w-init=header"  

Options:
  -h|--help       print this help text
  -o|--ow         only removes folders within single_subj workflow with "run-". If specific runs 
                  are requested with '-r', only these folders will be removed
  --clean         remove the single-subject workflow folder completely. This saves storage, but 
                  comes at the price that it re-runs EVERYTHING if you restart the process.
  --docker        run fmriprep through docker image (requires 'fmriprep-docker' to be installed!)
                  docker is not compatible with separate input folders for 'anat' and 'func', so 
                  the input folder will be set to DIR_DATA_HOME by default. The T1w that is 
                  present in the anat'-folder will be used as input.
  --func          same as '-t func'
  --sge           submit to SGE, if present.
  --no-bbr        maps to '--force-no-bbr' in call_fmriprep
  --remove-surf-wf  Remove surface reconstruction workflow folder; refreshes the surfaces used for 
                  registration and transformation
  --remove-wf     remove full single_subject workflow folder. Use \"--remove-surf-wf\" to 
                  specifically remove the surface reconstruction folder when you have new 
                  FreeSurfer output that fMRIPrep needs to use, or "--ow" to remove all folders 
                  within single_subj workflow with "run-"

Positional:
  <anat dir>      directory containing the anatomical data. Can also be the regular project root
                  folder if you want fMRIprep do the surface reconstruction
  <derivatives>   output folder for fMRIprep; generally this will be \$DIR_DATA_DERIV
  <mode>          run anatomical workflow only with 'anat', or everything with 'func'
  <T2 dir>        if you have a T2w-file, but that is not in <anat dir> (because you preprocessed
                  the T1w-file, but not the T2w-file), you can specify the directory where it lives
                  here. Generally this will be the same as <func dir>

Example:
  spinoza_fmriprep \$DIR_DATA_DERIV/masked_mp2rage \$DIR_DATA_DERIV \$DIR_DATA_HOME
  spinoza_fmriprep \\
    -s 001 \\
    -n 1 \\
    -f \$DIR_DATA_HOME \\
    \$DIR_DATA_DERIV/masked_mp2rage \$DIR_DATA_DERIV \$DIR_DATA_HOME

Call with master:
  # vanilla (runs --anat-only)
  master -m $(get_module_nr $(basename ${0})) -s 01
  
  # include FUNC & run via master with singularity and 15 cores
  master -m $(get_module_nr $(basename ${0})) -s 01 --func -j 15 --sge

  # run via master with docker
  master -m $(get_module_nr $(basename ${0})) -s 01 --func --docker

  # remove single subject workflow folder
  master -m $(get_module_nr $(basename ${0})) -s 01 --func -j 15 --sge --remove-wf

  # remove surface workflow folder
  master -m $(get_module_nr $(basename ${0})) -s 01 --func -j 15 --sge --remove-surf-wf

---------------------------------------------------------------------------------------------------

USAGE

}

if [[ $# -lt 2 ]] ; then
  Usage && exit 0
fi

# Check for subject & session flags
bbr_flag=""
run_local=1
kwargs_file=""
remove_wf=0
remove_surf_wf=0
OW=0
n_cpus=1
clean_wd=""
docker_flag=""
crash_flag=""
mode="anat"
workdir="${PATH_HOME}/fmriprep/${PROJECT}"
SGE_QUEUE="${SGE_QUEUE_LONG}"
kwargs_flag=""
dryrun_flag=""
while getopts :-:hols:r:n:f:m:j:k:q:u:a:w:x: argument
do
case ${argument} in
    -)
      case "${OPTARG}" in
        no-bbr)
          bbr_flag="--no-bbr"
          ;; 
        docker)
          docker_flag="--docker"
          ;; 
        sge)
          run_local=0
          ;;
        debug)
          dryrun_flag="--debug"
          run_local=1
          ;;          
        remove-wf)
          remove_wf=1
          ;; 
        remove-surf-wf)
          remove_surf_wf=1
          ;; 
        func)
          remove_surf_wf=1
          ;; 
        ow)
          OW=1
          ;;
        clean)
          clean_wd="--clean"
          ;;
        try)
          crash_flag="--try"
          ;; 
        help)
          Usage && exit 0
          ;;
        *)
          Usage
          print_error_msg "$(basename ${0})" "getopt" "Unknown option --${OPTARG}"
          exit 1
          ;;
      esac
      ;;
    h)  Usage && exit 0
          ;;
    s)  sub="${OPTARG}"
          ;;
    n)  ses="${OPTARG}"
          ;;
    f)  func_dir="${OPTARG}"
          ;;
    m)  mode="${OPTARG}"
          ;;
    u)  conf="${OPTARG}"
          ;;
    j)  n_cpus="${OPTARG}"
          ;; 
    k)  kwargs_file="${OPTARG}"
          ;;
    r)  runs="${OPTARG}"
          ;; 
    q)  SGE_QUEUE="${OPTARG}"
          ;; 
    w)  workdir="${OPTARG}"
          ;; 
    x)  kwargs_flag="${OPTARG}"
          ;;           
    o)  OW=1
          ;;
    a)  keep_runs="${OPTARG}"
          ;; 
  esac
done

shift "$((OPTIND - 1))"

if (( $# < 3 )); then
    Usage
    exit 1
fi

INPUT=$1
OUTPUT=$2
T2=$3

# check run
if [[ ! -z ${runs} ]]; then
  IFS=', ' read -r -a n_runs <<< "${runs}"
  unset IFS
fi

# get subjects
search=$(determine_subjects "$INPUT" "$SUBJECT_PREFIX" "$sub")

# Check if ${mode} represents a task ID instead of "anat" or "func"
task_id=""
if [[ -n ${mode} && ${mode} != "anat" && ${mode} != "func" ]]; then
  task_id="${mode}"
fi

# always run debugger locally
if [[ -n $dryrun_flag ]]; then
  run_local=1
fi

#-----------------------------------------------------------------------------
#intro
start_timer "Preprocessing with fMRIprep"

#-----------------------------------------------------------------------------
# loop through subjects
for subID in ${search}; do
  
  #-----------------------------------------------------------------------------
  # collect subject name
  sub_name=$(collect_subject_name "$sub" "$subID" "$SUBJECT_PREFIX")
  sub_id=$(get_subject_id "$sub" "$subID" "$SUBJECT_PREFIX")
  read base_path base <<< "$(collect_session_info "$ses" "$sub_name")"

  #-----------------------------------------------------------------------------
  # define input
  if [[ "${mode}" == "anat" ]]; then
    
    #-----------------------------------------------------------------------------
    # anat only
    input_dir="${INPUT}/${base_path}"
    func_txt="Only including anatomical data [${BOLD_GREEN}${input_dir}${RESET}]"
    check_and_copy_anat \
      "${func_dir}" \
      "${base_path}" \
      5 \
      "${FS}" \
      "${sub_name}" \
      "${base}" \
      "${DATA}"
  else
    #-----------------------------------------------------------------------------
    # include func
    if [[ -z "${func_dir}" ]]; then
      func_dir="${INPUT}"
    else
      INPUT="${func_dir}"
    fi

    input_dir="${func_dir}/${base_path}"

    # find func
    func=($(
      find_func_data \
      "${func_dir}" \
      "${base_path}" \
      "${input_dir}"
    ))

    func_txt="Including functional data [${#func[@]} files in ${BOLD_GREEN}${func_dir}${RESET}]"
    # anat still required
    check_and_copy_anat \
      "${func_dir}" \
      "${base_path}" \
      6 \
      "${FS}" \
      "${sub_name}" \
      "${base}" \
      "${DATA}"

    if [[ -z "${func}" || ${#func[@]} -eq 0 ]]; then
      print_file_not_in_dir "${sub_name}" "*bold.nii.gz" "${input_dir}/func" "Make sure the session ID (if applicable) is specified correctly and make sure to use \"-f <bids directory with BOLD data>\" to include functional data"
      continue
    fi
  fi

  #-----------------------------------------------------------------------------
  # intro
  if [[ ${run_local} -eq 1 ]]; then
    # print header
    print_subject_header ${sub_name}
    echo -e "${func_txt}"
  fi

  #-----------------------------------------------------------------------------
  # sort out working directory
  manage_fmriprep_workdir \
    "${workdir}" \
    "${project}" \
    "${sub_id}" \
    "${remove_surf_wf}" \
    "${remove_wf}" \
    "${overwrite}" \
    "${run_local}" \
    "${n_runs[@]}"

  #-----------------------------------------------------------------------------
  # check configuration file
  confFile="$(
    generate_config_file \
    "${conf}" \
    "${n_runs[@]}"
  )"

  #-----------------------------------------------------------------------------
  # decide the job type
  job="$(
    decide_job_type \
    "call_fmriprep" \
    "${sub_name}_desc-fmriprep" \
    "${run_local}" \
    "${workdir}" \
    "${n_cpus}" \
    "${SGE_QUEUE}"
  )"

  #-----------------------------------------------------------------------------
  # define the command
  cmd=(
    "${job}"
    -s "$sub_id"
    -m "$mode"
    -b "$FPREP_BINDING"
    -r "$INPUT"
    -d "$OUTPUT"
    -w "$workdir"
    -c "$n_cpus"
  )

  [[ -n ${keep_runs:-} ]]   && cmd+=(-a "$keep_runs")
  [[ -n ${task_id:-} ]]     && cmd+=(-t "$task_id")
  [[ -n ${kwargs_file:-} ]] && cmd+=(-k "$kwargs_file")
  [[ -n ${crash_flag:-} ]]  && cmd+=("$crash_flag")
  [[ -n ${bbr_flag:-} ]]    && cmd+=("$bbr_flag")
  [[ -n ${clean_wd:-} ]]    && cmd+=("$clean_wd")
  [[ -n ${func_flag:-} ]]   && cmd+=("$func_flag")
  [[ -n ${anat_flag:-} ]]   && cmd+=("$anat_flag")
  [[ -n ${docker_flag:-} ]] && cmd+=("$docker_flag")
  [[ -n ${dryrun_flag:-} ]] && cmd+=("$dryrun_flag") && echo -e "${BOLD_RED}DEBUG MODE ENABLED${RESET}" && echo

  if [[ -n $confFile ]]; then
    cmd+=(-y "$confFile")
  fi

  if [[ -n ${kwargs_flag:-} ]]; then
      cmd+=(-x "$kwargs_flag")
  fi

  # clean up
  clean_cmd=()
  for arg in "${cmd[@]}"; do
      [[ -n $arg ]] && clean_cmd+=("$arg")
  done

  cmd=("${clean_cmd[@]}")

  #-----------------------------------------------------------------------------
  # echo cmd
  if [[ ${run_local} -eq 1 ]]; then
    print_cmd "${cmd[@]}"
  fi
  
  # run
  eval "${cmd[@]}"
  if [[ $? -ne 0 ]]; then
    print_error_msg "$(basename ${0})" "call_fmriprep"
    exit 1
  fi

done

#-----------------------------------------------------------------------------
# outro
end_timer
